GOOGLE_CREDENTIALS = """
{
  "type": "service_account",
  "project_id": "ksvcsapplyassistance",
  "private_key_id": "f375e46287c814e9cabb7454b690f21718e39ec3",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQC1gQKjfW4TOM1l\n2wyGfafNaJe8ptXGYcD6zy8/hM9nzqJegiaELgcKAPfqXIYr+GNgGy/7pbw5IoMw\nkcU0QggQfEaP3jUz9NRiBYN6PDh4iYGsa4WMX1dzGcJI1uLcX3zI6YGsYIkodyBW\nJLI6lrZrFpPxW7cOc3RzyzleunJssQ0I/2DWmm7rT0oO92zG/3pUkMUngK5Slv/8\no+1m7hnFWoF5WQjNJH4SKhcUrjvzOmNgoJS41qe9RAAHFtvyxXZY1PBTOhl1WSxi\nAwxq9/tM1d08v5Eef2tzJgfa6FkltjW0wqblgzJi8A2Jt9FNPlC0eZ30vRHn36SL\nDpOuvNZFAgMBAAECggEADCZVqeIEk07TGQVfwkT5DZv5xEwatUvn4iIqVIMsaxN+\n...
  "client_email": "id-14-apply-assistance@ksvcsapplyassistance.iam.gserviceaccount.com",
  "client_id": "110868177380757060088",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/id-14-apply-assistance%40ksvcsapplyassistance.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
"""
