[GOOGLE_CREDENTIALS]
type = "service_account"
project_id = "ksvcsapplyassistance"
private_key_id = "f375e46287c814e9cabb7454b690f21718e39ec3"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQC1gQKjfW4TOM1l
2wyGfafNaJe8ptXGYcD6zy8/hM9nzqJegiaELgcKAPfqXIYr+GNgGy/7pbw5IoMw
kcU0QggQfEaP3jUz9NRiBYN6PDh4iYGsa4WMX1dzGcJI1uLcX3zI6YGsYIkodyBW
JLI6lrZrFpPxW7cOc3RzyzleunJssQ0I/2DWmm7rT0oO92zG/3pUkMUngK5Slv/8
o+1m7hnFWoF5WQjNJH4SKhcUrjvzOmNgoJS41qe9RAAHFtvyxXZY1PBTOhl1WSxi
Awxq9/tM1d08v5Eef2tzJgfa6FkltjW0wqblgzJi8A2Jt9FNPlC0eZ30vRHn36SL
DpOuvNZFAgMBAAECggEADCZVqeIEk07TGQVfwkT5DZv5xEwatUvn4iIqVIMsaxN+
9PqbX2/BUt8buVl2Nc1LwawwOxUuE1kHFSI85DGjXo8jHhBO2WqDKQibc3xCf3cc
8hDEgNAFB5Rq1/tidkQCE2TmJEbWB5pp1LpiH9/k2ChLwPVVvKbn3bR146xxamsW
p6g3ZMQ++1NB8LK5uqZck7to8X5+WOu3FcGx36Rt6QZEu2WZjWJbq+PlP/iiYSEY
fSKxxCAw2fGRrr/PRrQWvGwlOBhclOuruBgioK642qnBucRerzepQIVGNySfNrRf
9TZHo9l8+ZrZtq21GPKnLP3SRhOmLXftX64Mewcg5QKBgQDt1B9sLdy+V6DIG5QV
hKw6PGD/uOXepqT+ie6xkj4ytCrNOJe7LvHMfmkm08OL8HlfZX7E9zMpDV+BtY3R
Hp6h0FzpSCdXbqjRM01FbYfkesOFFTPW1MILTr6zGallOBBWT8GubVoChsocv7CX
iPQYqzMUEceszJhHeJzPRZxy6wKBgQDDXzBsWDuw87gA/Y+qRnaKm3wAM0qVWgMp
Vbf/eQ2lRoL9Y+xfIAqZ3vBuP4XjqwUUMKHYsfGh7Nki291N5/iHl6XbQ3fJtmD1
BJY5UQn/DEYGBP6Zzw8aOSWjvfzREmBzZ6yZWCzfnhHKL6gfD4XodjkaBwanKBxO
rnV+Ft6vjwKBgQCXEm27bA6SolsxgcM5QAOfIoeDKVJrcnPQdJG5HmqADs45ej93
2cQi4BGvZkkK9YBDxtcWCujmpOYMIOWq9sZRh2fdj8Xd1h9KdEobVg5CZnEYcnVx
e8ifIjAk2KIv98L48MTZJgFNJY3xYRqtx4M2wFk74Gd0Lqp0i/sf9toAbQKBgQCc
bIJgvORN8VTJtjpoorIWmBbYMjjtC3ysg60mJs3+Hk6SgoamQwk52X23R7Tza+JN
IAL1dMN6WiAgANlXnvsl1Q0+WO532kYW5u1ARtoyEqmd+DHBBD+bR1YTm/Hnk0cW
H1PaEvcas3ya3T1GYS9dyApABJAXFc5UUOpRYg45kQKBgQC4GcO473/7aDzL2KMX
Dcsv0LU+f4BPHul1dz9+SutSJ6ZOdQ6BfQzpdjvIyWa2WWesglT9bt2vaMR0iVsE
TgsppCT2TyZAVhbcuplm2pglSusdIMoa7lo3qipZTfuXbDYiKP4DlgqRnLAv8NL5
TUoqnq2lR1JKI4rAkeguHUSsXQ==
-----END PRIVATE KEY-----
"""
client_email = "id-14-apply-assistance@ksvcsapplyassistance.iam.gserviceaccount.com"
client_id = "110868177380757060088"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/id-14-apply-assistance%40ksvcsapplyassistance.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
